[0:thermal-in-normal.conf]
[1:thermal-in-huanji.conf]
[2:thermal-in-abnormal.conf]
[3:thermal-in-nightvideo.conf]
[4:thermal-in-dolbyvision.conf]
[5:thermal-in-phone.conf]
[6:thermal-in-nolimits.conf]
[7:thermal-in-class0.conf]
[8:thermal-in-youtube.conf]
[9:thermal-in-arvr.conf]
[10:thermal-in-navigation.conf]
[11:thermal-in-video.conf]
[12:thermal-in-demo.conf]
[13:thermal-in-sptm.conf]
[14:thermal-in-videochat.conf]
[15:thermal-in-camera.conf]
[16:thermal-in-4k.conf]
[17:thermal-in-4k.conf]
[18:thermal-in-tgame.conf]
[19:thermal-in-mgame.conf]
[20:thermal-in-yuanshen.conf]
[25:thermal-in-xingtie.conf]
[26:thermal-in-highfps.conf]
[27:thermal-in-charge.conf]
[50:thermal-in-per-normal.conf]
[52:thermal-in-per-abnormal.conf]
[57:thermal-in-per-class0.conf]
[58:thermal-in-per-youtube.conf]
[60:thermal-in-per-navigation.conf]
[61:thermal-in-per-video.conf]
[75:thermal-in-xingtie.conf]
[76:thermal-in-highfps.conf]
[500:thermal-in-hp-normal.conf]
[501:thermal-in-hp-mgame.conf]
[700:thermal-in-cgame.conf]
[701:thermal-in-cclassvideo.conf]
[702:thermal-in-cgame.conf]
