[0:thermal-normal.conf]
[1:thermal-huanji.conf]
[2:thermal-abnormal.conf]
[3:thermal-nightvideo.conf]
[4:thermal-dolbyvision.conf]
[5:thermal-phone.conf]
[6:thermal-nolimits.conf]
[7:thermal-class0.conf]
[8:thermal-youtube.conf]
[9:thermal-arvr.conf]
[10:thermal-navigation.conf]
[11:thermal-video.conf]
[12:thermal-demo.conf]
[13:thermal-sptm.conf]
[14:thermal-videochat.conf]
[15:thermal-camera.conf]
[16:thermal-4k.conf]
[17:thermal-4k.conf]
[18:thermal-tgame.conf]
[19:thermal-mgame.conf]
[20:thermal-yuanshen.conf]
[25:thermal-xingtie.conf]
[26:thermal-highfps.conf]
[27:thermal-charge.conf]
[28:thermal-extravideo.conf]
[50:thermal-per-normal.conf]
[52:thermal-per-abnormal.conf]
[57:thermal-per-class0.conf]
[58:thermal-per-youtube.conf]
[60:thermal-per-navigation.conf]
[61:thermal-per-video.conf]
[75:thermal-xingtie.conf]
[76:thermal-highfps.conf]
[78:thermal-extravideo.conf]
[500:thermal-hp-normal.conf]
[501:thermal-hp-mgame.conf]
[700:thermal-cgame.conf]
[701:thermal-cclassvideo.conf]
[702:thermal-cgame.conf]
